name: "Push ğŸ—"
description: "Push docker image to docker hub"
runs:
    using: composite
    steps:
      - name: Login to Docker Hub ğŸ”‘
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Publish to Docker Hub ğŸ›«
        working-directory:  ${{ env.PROJECT_DIRECTORY }}
        shell: bash
        run: |-
          docker push ${{ env.DOCKER_TAG }}:latest
          docker push ${{ env.DOCKER_TAG }}:${{ github.sha }}

